swagger: "2.0"
info:
  version: "0.0.1"
  title: web-back
host: web-back.eu-gb.cf.appdomain.cloud:8080
basePath: /v1/api
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /posts:
    x-swagger-router-controller: posts
    get:
      description: gets all posts
      operationId: findAll
      responses:
        "200":
          description: Returned existing user profile
          schema:
            $ref: "#/definitions/PostResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    post:
      description: add a post
      operationId: add
      parameters:
        - in: body
          name: post
          description: The post to add
          required: true
          schema:
            $ref: "#/definitions/PostModel"
      responses:
        "200":
          description: Returned existing user profile
          schema:
            $ref: "#/definitions/PostResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
definitions:
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
  PostModel:
    type: object
    properties:
      title:
        type: string
  PostResponse:
    type: object
    properties:
      id:
        type: string
      title:
        type: string
